sunday_market/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/sign_up', to: 'users#new', as: 'signup'
  root to: 'pages#home'
  # Session routes for Authenticatable (default)
  devise_scope :user do
    get '/sign_in', to: 'devise/sessions#new', as: 'signin'
    post '/sign_in', to: 'devise/sessions#create', as: 'create_session'
    get '/sign_out', to: 'devise/sessions#destroy', as: 'signout'
  end
  get '/restricted', to: 'pages#restricted'
  get '/users/:id', to: 'users#show'
  # put '/users/:id', to: 'users#update'
  # get '/users/:id', to: 'users#destroy'
  get '/listings', to: 'listings#index', as: 'listings'
  post '/listings', to: 'listings#create'
  get '/listings/new', to: 'listings#new', as: 'new_listing'
  # post '/listings', to: 'listings#index'
  get '/listings/:id', to: 'listings#show', as: 'listing'
  put '/listings/:id', to: 'listings#update'
  patch '/listings/:id', to: 'listings#update'
  delete '/listings/:id', to: 'listings#destroy', as: 'delete_listing'
  get '/listings/:id/edit', to: 'listings#edit', as: 'edit_listing'

 end

sunday_market/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sunday_market/app/models/category.rb
class Category < ApplicationRecord
    has_many :listings
end

sunday_market/app/models/listing.rb
class Listing < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_one :order
    has_one_attached :image
    
    enum condition: {
        excellent: 0,
        good: 1,
        fair: 2,
        poor:3
    }

    validates :title, :description, :price, :condition, :category, presence: true 
    validates :title, length: {maximum: 100}

    private
    
    def remove_whitespace 
        self.title = self.title.strip
        self.description = self.description.strip
    end

    def convert_price_to_cents 
        self.price = (self.attributes_before_type_cast["price"].to_f * 100).round
    end
end

sunday_market/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :listing
  belongs_to :user
end

sunday_market/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
  has_many :order
end

sunday_market/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    

end

sunday_market/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

sunday_market/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :set_listing, only: [:show, :edit, :update, :destroy]
    skip_before_action :verify_authenticity_token
    before_action :set_conditions, only: [:new, :edit]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy] #-> user has to "login" to access app
    #show all the resources
    def index
        @listings = Listing.all
    end

    # get /listing/1 (Showing one of the resources)
    # def show
    #     found_listing = listings.find do |listing|
    #         listing[:id] == params[:id]
    #     end

    #     # add in print found_listing
    # end
    def show
    end

    # get /listings/new (to have a form that allow you to create new resource)
    def new
        @listing = Listing.new
    end 

    # def create
    #     @listing = Listing.create!(listing_params)
    #     redirect_to listings_path
    # end

    def create
        @listing = current_user.listings.new(listing_params)
            if @listing.save 
                redirect_to @listing, notice: "Listing successfully created"
            else
                set_form_vars
                render "new", notice: "Sorry, Something went wrong. Make sure your form is completely filled in before submitting"
            end
    end
    
    # get /listings/1/edit
    def edit

    end

    def update 
        @listing.update(listing_params)
        if @listing.save 
            redirect_to @listing, notice: "Listing successfully updated"
        else
            set_form_vars
            render "edit", notice: "Something went wrong"
        end 
    end

    # DELETE /listing/1
    def destroy
        @listing.destroy
        redirect_to listings_path, notice: "Listing successfully deleted"
    end

    private
    
    def set_listing
        @listing = Listing.find(params[:id])
    end

    def listing_params
        params.require(:listing).permit(:user_id, :title, :description, :price, :condition, :category_id, :sold, :image)
    end

    def set_conditions
        @conditions = Listing.conditions.keys
    end

    def set_categories
        @categories = Category.names
    end

    def set_form_vars
        @categories = Category.all
        @conditions = Listing.conditions.keys
    end

end

sunday_market/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

sunday_market/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:restricted]
  
  def home

  end

  def restricted

  end
end

sunday_market/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        # index is for sending back ALL the resources
        render @user
    end


    def new
        @user = User.create
    end

    def show
        all_users = User.all
    end


    

end

sunday_market/app/helpers/application_helper.rb
module ApplicationHelper
end

sunday_market/app/helpers/categories_helper.rb
module CategoriesHelper
end

sunday_market/app/helpers/listings_helper.rb
module ListingsHelper
end

sunday_market/app/helpers/orders_helper.rb
module OrdersHelper
end

sunday_market/app/helpers/pages_helper.rb
module PagesHelper
end

sunday_market/app/helpers/users_helper.rb
module UsersHelper
end

sunday_market/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SundayMarket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "partials/navbar" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

sunday_market/app/views/listings/_form.html.erb
<%# form_with is a partial and helps build a form with many functions %>
<%# This form takes in the model listings %>
<%= form_with model: listing do |f| %>

    <div>
    <%# Hidden fields to help capture these details in the back-end but not to be displayed in front-end %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :sold, value: false %>
        <br>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <br>
        <%= f.label :description %>
        <%= f.text_area :description %>
        <br>
        <p>Select the condition of your listing:</p>
        <% for option in conditions %>
        <%# Radio buttons provided for conditions to help with providing buyer in the search function (To be implemented in future) %>
            <div>
                <%= f.radio_button :condition, option %>
                <%= f.label "condition#{option}".to_sym, option %>
            </div>
        <% end %>
        <%# Category has a drop down function to stop users from typing in anything and helps future search functions %>
        <br>
            <%= f.label "Select the category of your listing:" %>
            <%= f.collection_select :category_id, Category.order(:name),:id,:name %>
        <br>
        <%= f.label :price %>
        <%# There is a min and max amount on the uers listing %>
        <%= f.number_field :price, min: 0, max: 10000 %>
        <br>
        <%# File upload is restricted to png, jpg, jpeg files only %>
        <%= f.file_field :image, accept: "image/png, image/jpg, image/jpeg" %>
        <br>
        <%= f.submit "Save Listing" %>
    </div>

<% end %>

sunday_market/app/views/listings/edit.html.erb
<h1> Make changes to your listing </h1>
<%# Render form allows the same form to be used for two different purposes: Create new listing and Editing listing %>
<%= render "form", listing: @listing, conditions: @conditions, categories: @categories %>
<br>
<%# This delete button offers users second chance to ensure the delete action is intentional and not a mistake %>
<%= link_to "Delete Listing", @listing, method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger" %>

<%=link_to "Home", root_path%>

sunday_market/app/views/listings/index.html.erb
<h1>All Listings</h1>
<%# Using Bootstrap to style using card / grid styling %>
<div class="row">
    <% @listings.each do |listing| %>
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <div class="listings-image">
                <%# This logic ensures that an default image is provided if no image for listing was provided %>
                    <% if listing.image.attached? %>
                        <%= link_to image_tag(listing.image, alt: listing.title), listing_path(listing.id) %>
                    <% else %>
                        <%= link_to image_tag("listing_default.jpeg", alt: "Sunday Market Listing"), listing_path(listing.id) %>
                    <% end %>
                </div>
                <div class="listings-body">
                    <h3><%= link_to listing.title, listing_path(listing.id) %></h3>
                    <p><%= listing.description %></p>
                    <%# Converts integer to currency %>
                    <h4><%= number_to_currency(listing.price) %></h4>
                    <%= link_to "See More", listing_path(listing.id), class:"btn btn-primary" %>
                </div>
            </div>
        </div>
    <% end %>
</div>

sunday_market/app/views/listings/new.html.erb
<h1> Create A New Listing to Sell </h1>
<%# Render form allows the same form to be used for two different purposes: Create new listing and Editing listing %>
<%# Keeping code DRY and effiency in updating the format of forms in this application and reduces the chances of human error%>
<%= render "form", listing: @listing, conditions: @conditions, categories: @categories %>

sunday_market/app/views/listings/show.html.erb
<h1> Show Listing </h1>

<p>
    <strong>Title:</strong>
    <%= @listing.title%>
</p>

<p>
    <strong>Description:</strong>
    <%= @listing.description%>
</p>

<p>
    <strong>Condition:</strong>
    <%= @listing.condition%>
</p>

<p>
    <strong>Category:</strong>
    <%= @listing.category.name%>
</p>

<p>
    <strong>Price:</strong>
    <%= @listing.price%>
</p>

<p>
    <strong>Owner:</strong>
    <%= @listing.user.email%>
</p>

<p>
    <% if @listing.image.attached? %>
        <%= image_tag @listing.image %>
    <% else %>
        <%= image_tag("listing_default.jpeg", alt: "Sunday Market Listing") %>
    <% end %>
</p>
<% if current_user && (current_user.id == @listing.user_id) %>
    <%= link_to "Edit", edit_listing_path(@listing) %>
<% end %>
<%= link_to "Back", listings_path %>

sunday_market/app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-md-6">
      <h1 class="display-4">Sunday Market</h1>
      <p class="lead"> Browse the Sunday Market. Buy arts, sell arts, support your local artist. </p>
      <hr class="my-4">
      <p class="lead">
        <%= link_to "View Listings", listings_path, class:"btn btn-primary btn-lg" %>
        <%= link_to "Create Listing", new_listing_path, class:"btn btn-primary btn-lg" %>
      </p>
    </div>

    <div class="col-md-6">
      <%= image_tag "ceramic.jpg", class: "home-image" %>
    </div> 
  </div>
</div>

sunday_market/app/views/partials/_navbar.html.erb
<%# Navbar styling by Bootstrap %>
<%# Navbar created as partials to help ease in displaying on all pages for conistency %>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Sunday Market</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    <%# This logic allow users to only see what they are allowed, depending on if they are signed in. This will determined what they are authorised to see and authorised to execute certain functions %>
      <% if current_user %>
        Logged in as <%= current_user.email %>
        <%= link_to "Sign Out", signout_path, class: "nav-item nav-link" %>
        <%= link_to "Create Listing", new_listing_path, class: "nav-item nav-link" %>
      <% else %>
        <%= link_to "Sign In", signin_path, class: "nav-item nav-link" %>
        <%= link_to "Sign up", '/users/sign_up', class: "nav-item nav-link" %>
      <% end %>
      <%= link_to "View Listings", listings_path, class: "nav-item nav-link" %>
    </div>
  </div>
</nav>